version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: multilane_kafka_zookeeper
    networks:
      - app-tier
    ports:
      - 127.0.0.1:2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: wurstmeister/kafka:latest
    container_name: multilane_kafka_kafka
    networks:
      - app-tier
    depends_on:
      - zookeeper
    ports:
      - 127.0.0.1:9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka

################################# base-line #################################
  app-a-base-line:
    image: multi-lanes-demo-kafka-app-a
    networks:
      - app-tier
    ports:
      - 127.0.0.1:9001:9001
    container_name: multi-lanes-demo-kafka-app-a_base_line
    depends_on:
      - zookeeper
      - kafka
    environment:
      CONFIG_FORCE_featureTag: base
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
      CONFIG_FORCE_kafka.brokers: kafka:9092
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-kafka-app-a.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it


  app-b-base-line:
    image: multi-lanes-demo-kafka-app-b
    networks:
      - app-tier
    ports:
      - 127.0.0.1:9002:9002
    container_name: multi-lanes-demo-kafka-app-b_base_line
    depends_on:
      - zookeeper
      - kafka
    environment:
      CONFIG_FORCE_featureTag: base
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
      CONFIG_FORCE_kafka.brokers: kafka:9092
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-kafka-app-b.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it


  app-c-base-line:
    image: multi-lanes-demo-kafka-app-c
    networks:
      - app-tier
    ports:
      - 127.0.0.1:9003:9003
    container_name: multi-lanes-demo-kafka-app-c_base_line
    depends_on:
      - zookeeper
      - kafka
    environment:
      CONFIG_FORCE_featureTag: base
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
      CONFIG_FORCE_kafka.brokers: kafka:9092
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-kafka-app-c.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it


  app-d-base-line:
    image: multi-lanes-demo-kafka-app-d
    networks:
      - app-tier
    ports:
      - 127.0.0.1:9004:9004
    container_name: multi-lanes-demo-kafka-app-d_base_line
    depends_on:
      - zookeeper
      - kafka
    environment:
      CONFIG_FORCE_featureTag: base
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
      CONFIG_FORCE_kafka.brokers: kafka:9092
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-kafka-app-d.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it

################################# feature-x-line #################################

  app-b-feature-x-line:
    image: multi-lanes-demo-kafka-app-b
    networks:
      - app-tier
    ports:
      - 127.0.0.1:9102:9002
    container_name: multi-lanes-demo-kafka-app-b_feature-x_line
    depends_on:
      - zookeeper
      - kafka
    environment:
      CONFIG_FORCE_featureTag: feature-x
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
      CONFIG_FORCE_kafka.brokers: kafka:9092
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-kafka-app-b.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it

  app-d-feature-x-line:
    image: multi-lanes-demo-kafka-app-d
    networks:
      - app-tier
    ports:
      - 127.0.0.1:9104:9004
    container_name: multi-lanes-demo-kafka-app-d_feature-x_line
    depends_on:
      - zookeeper
      - kafka
    environment:
      CONFIG_FORCE_featureTag: feature-x
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
      CONFIG_FORCE_kafka.brokers: kafka:9092
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-kafka-app-d.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it