version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - app-tier
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - app-tier
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672


################################# base-line #################################
  app-a-base-line:
    image: multi-lanes-demo-rabbitmq-app-a
    networks:
      - app-tier
    ports:
      - 8006:8006
    container_name: multi-lanes-demo-rabbitmq-app-a_base_line
    depends_on:
      - zookeeper
      - rabbitmq
    environment:
      spring_rabbitmq_host: rabbitmq
      CONFIG_FORCE_featureTag: base
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-rabbitmq-app-a.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it


  app-b-base-line:
    image: multi-lanes-demo-rabbitmq-app-b
    networks:
      - app-tier
    ports:
      - 8007:8007
    container_name: multi-lanes-demo-rabbitmq-app-b_base_line
    depends_on:
      - zookeeper
      - rabbitmq
    environment:
      spring_rabbitmq_host: rabbitmq
      CONFIG_FORCE_featureTag: base
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-rabbitmq-app-b.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it


  app-c-base-line:
    image: multi-lanes-demo-rabbitmq-app-c
    networks:
      - app-tier
    ports:
      - 8008:8008
    container_name: multi-lanes-demo-rabbitmq-app-c_base_line
    depends_on:
      - zookeeper
      - rabbitmq
    environment:
      spring_rabbitmq_host: rabbitmq
      CONFIG_FORCE_featureTag: base
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-rabbitmq-app-c.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it


  app-d-base-line:
    image: multi-lanes-demo-rabbitmq-app-d
    networks:
      - app-tier
    ports:
      - 8009:8009
    container_name: multi-lanes-demo-rabbitmq-app-d_base_line
    depends_on:
      - zookeeper
      - rabbitmq
    environment:
      spring_rabbitmq_host: rabbitmq
      CONFIG_FORCE_featureTag: base
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-rabbitmq-app-d.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it

################################# feature-x-line #################################

  app-b-feature-x-line:
    image: multi-lanes-demo-rabbitmq-app-b
    networks:
      - app-tier
    ports:
      - 8017:8007
    container_name: multi-lanes-demo-rabbitmq-app-b_feature-x_line
    depends_on:
      - zookeeper
      - rabbitmq
    environment:
      spring_rabbitmq_host: rabbitmq
      CONFIG_FORCE_featureTag: feature-x
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-rabbitmq-app-b.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it

  app-d-feature-x-line:
    image: multi-lanes-demo-rabbitmq-app-d
    networks:
      - app-tier
    ports:
      - 8019:8009
    container_name: multi-lanes-demo-rabbitmq-app-d_feature-x_line
    depends_on:
      - zookeeper
      - rabbitmq
    environment:
      spring_rabbitmq_host: rabbitmq
      CONFIG_FORCE_featureTag: feature-x
      CONFIG_FORCE_spring.cloud.zookeeper.connectString: zookeeper:2181
    entrypoint: [ "sh", "/wait-for-it/wait-for-infras.sh", "--", "sh", " /wait-for-it/run.sh", "multi-lanes-demo-rabbitmq-app-d.jar"]
    volumes:
      - ./wait-for-it:/wait-for-it